#!/bin/bash

# Hyprland Autostart Script
# Auto-generated by Arch Linux Hyprland Setup Script

# Kill any existing instances
killall -q waybar
killall -q mako
killall -q hyprpaper
killall -q nm-applet

# Wait for processes to terminate
while pgrep -x waybar >/dev/null; do sleep 1; done
while pgrep -x mako >/dev/null; do sleep 1; done

# Environment setup
export XDG_CURRENT_DESKTOP=Hyprland
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=Hyprland

# Start core services
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &

# Start applications
waybar -c ~/.config/waybar/config-primary.jsonc -s ~/.config/waybar/style.css &
waybar -c ~/.config/waybar/config-secondary.jsonc -s ~/.config/waybar/style.css &
mako &
hyprpaper &
nm-applet &
/usr/lib/polkit-kde-authentication-agent-1 &

# Clipboard history
wl-paste --type text --watch cliphist store &
wl-paste --type image --watch cliphist store &

# Idle management
hypridle &

# Audio setup
systemctl --user enable --now pipewire pipewire-pulse wireplumber &