#!/bin/bash

# Dotfiles Symlink Manager
# Auto-generated by Arch Linux Hyprland Setup Script

set -euo pipefail

# Configuration
DOTFILES_DIR="$HOME/.dotfiles"
CONFIG_FILE="$DOTFILES_DIR/.symlink-config"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
NC='\033[0m'

# Print functions
print_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_header() {
    echo -e "${PURPLE}$1${NC}"
    echo "$(printf '=%.0s' {1..60})"
}

print_usage() {
    echo "Dotfiles Symlink Manager"
    echo "Usage: $0 <command> [options]"
    echo ""
    echo "Commands:"
    echo "  setup                   Initialize dotfiles repository"
    echo "  add <path>             Add file/directory to dotfiles"
    echo "  remove <path>          Remove file/directory from dotfiles"
    echo "  link                   Create all symlinks"
    echo "  unlink                 Remove all symlinks"
    echo "  status                 Show symlink status"
    echo "  list                   List managed files"
    echo "  sync                   Sync with git repository"
    echo "  clone <repo_url>       Clone existing dotfiles repository"
    echo "  backup                 Backup current dotfiles"
    echo "  restore                Restore from backup"
    echo ""
    echo "Examples:"
    echo "  $0 setup                                    # Initialize new dotfiles repo"
    echo "  $0 add ~/.config/hypr                       # Add Hyprland config"
    echo "  $0 add ~/.config/waybar/config-primary.jsonc # Add specific file"
    echo "  $0 remove ~/.config/fish                    # Remove from dotfiles"
    echo "  $0 clone https://github.com/user/dotfiles   # Clone existing repo"
}

# Initialize dotfiles repository
setup_dotfiles() {
    print_header "Setting up dotfiles repository"
    
    if [ -d "$DOTFILES_DIR" ]; then
        print_warning "Dotfiles directory already exists: $DOTFILES_DIR"
        print_info "Use 'link' command to create symlinks or 'clone' to replace with existing repo"
        return
    fi
    
    # Create dotfiles directory
    mkdir -p "$DOTFILES_DIR"
    cd "$DOTFILES_DIR"
    
    # Initialize git repository
    git init
    
    # Create directory structure
    mkdir -p config/{hypr,waybar,fish,matugen,mako,wofi,kitty}
    mkdir -p scripts
    mkdir -p themes
    mkdir -p backup
    
    # Create README
    cat > README.md << 'EOF'
# My Dotfiles

Personal configuration files for Hyprland desktop environment.

## Installation

```bash
# Clone the repository
git clone <your-repo-url> ~/.dotfiles

# Run the symlink manager
~/.dotfiles/scripts/symlink-manager.sh link
