# Right-side Fish Prompt
# Auto-generated by Arch Linux Hyprland Setup Script

function fish_right_prompt --description 'Right side prompt for additional info'
    set -l last_status $status
    set -l normal (set_color normal)
    set -l red (set_color red)
    set -l yellow (set_color yellow)
    set -l green (set_color green)
    set -l blue (set_color blue)
    set -l gray (set_color -o black)
    
    # Command duration (if available)
    set -l cmd_duration_info ""
    if set -q CMD_DURATION
        if test $CMD_DURATION -gt 5000
            set -l duration_sec (math $CMD_DURATION / 1000)
            if test $duration_sec -gt 60
                set -l duration_min (math $duration_sec / 60)
                set cmd_duration_info " $yellow⏱ "(math $duration_min)"m$normal"
            else
                set cmd_duration_info " $yellow⏱ "(math $duration_sec)"s$normal"
            end
        end
    end
    
    # Jobs indicator
    set -l jobs_info ""
    set -l job_count (jobs | wc -l)
    if test $job_count -gt 0
        set jobs_info " $blue⚙ $job_count$normal"
    end
    
    # Git status on right side (minimal)
    set -l git_right_info ""
    if command -sq git
        set -l git_dir (git rev-parse --git-dir 2>/dev/null)
        if test -n "$git_dir"
            set -l ahead_behind (git rev-list --left-right --count HEAD...@{upstream} 2>/dev/null)
            if test -n "$ahead_behind"
                set -l ahead (echo $ahead_behind | cut -f1)
                set -l behind (echo $ahead_behind | cut -f2)
                
                if test $ahead -gt 0; and test $behind -gt 0
                    set git_right_info " $yellow↕$normal"
                else if test $ahead -gt 0
                    set git_right_info " $green↑$ahead$normal"
                else if test $behind -gt 0
                    set git_right_info " $red↓$behind$normal"
                end
            end
        end
    end
    
    # Kubernetes context (if available)
    set -l k8s_info ""
    if command -sq kubectl
        set -l k8s_context (kubectl config current-context 2>/dev/null)
        if test -n "$k8s_context"; and test "$k8s_context" != "docker-desktop"
            set k8s_info " $blue☸ "(echo $k8s_context | cut -c1-8)"$normal"
        end
    end
    
    # AWS profile (if set)
    set -l aws_info ""
    if set -q AWS_PROFILE; and test "$AWS_PROFILE" != "default"
        set aws_info " $yellow☁ $AWS_PROFILE$normal"
    end
    
    # Combine all elements
    printf '%s%s%s%s%s' $cmd_duration_info $jobs_info $git_right_info $k8s_info $aws_info
end