# Fish Shell Configuration
# Auto-generated by Arch Linux Hyprland Setup Script

# Disable greeting message
set fish_greeting

# Set default editor
set -gx EDITOR nvim
set -gx VISUAL nvim

# Set XDG directories
set -gx XDG_CONFIG_HOME $HOME/.config
set -gx XDG_DATA_HOME $HOME/.local/share
set -gx XDG_CACHE_HOME $HOME/.cache

# Wayland environment variables
set -gx MOZ_ENABLE_WAYLAND 1
set -gx QT_QPA_PLATFORM wayland
set -gx XDG_CURRENT_DESKTOP Hyprland
set -gx XDG_SESSION_DESKTOP Hyprland
set -gx XDG_SESSION_TYPE wayland

# Path configuration
fish_add_path $HOME/.local/bin
fish_add_path $HOME/.cargo/bin
fish_add_path $HOME/go/bin

# Modern CLI tool aliases
if command -q eza
    alias ls='eza --icons --group-directories-first'
    alias ll='eza --icons --group-directories-first -l'
    alias la='eza --icons --group-directories-first -la'
    alias lt='eza --icons --group-directories-first --tree'
    alias ltl='eza --icons --group-directories-first --tree -l'
end

if command -q bat
    alias cat='bat --style=plain --paging=never'
    alias batl='bat --style=numbers,changes --paging=auto'
end

if command -q fd
    alias find='fd'
end

if command -q ripgrep
    alias grep='rg'
end

# Git aliases
alias g='git'
alias ga='git add'
alias gaa='git add --all'
alias gc='git commit -v'
alias gcm='git commit -m'
alias gco='git checkout'
alias gd='git diff'
alias gl='git pull'
alias gp='git push'
alias gs='git status'
alias gst='git stash'
alias gstp='git stash pop'
alias gb='git branch'
alias gba='git branch -a'
alias gbd='git branch -d'
alias glog='git log --oneline --decorate --graph'
alias gloga='git log --oneline --decorate --graph --all'

# System aliases
alias c='clear'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias ~='cd ~'
alias h='history'
alias j='jobs'
alias l='ls'
alias q='exit'
alias reload='source ~/.config/fish/config.fish'

# Package management aliases
alias pac='sudo pacman'
alias pacs='sudo pacman -S'
alias pacu='sudo pacman -Syu'
alias pacr='sudo pacman -R'
alias pacrs='sudo pacman -Rs'
alias pacss='pacman -Ss'
alias pacsi='pacman -Si'
alias pacqs='pacman -Qs'
alias pacqi='pacman -Qi'
alias yayi='yay -S'
alias yayu='yay -Syu'
alias yays='yay -Ss'

# Hyprland specific aliases
alias hypreload='hyprctl reload'
alias hyprkill='hyprctl kill'
alias wmclass='hyprctl clients | grep class'

# Useful functions
function mkcd
    mkdir -p $argv[1] && cd $argv[1]
end

function extract
    switch $argv[1]
        case "*.tar.bz2"
            tar xjf $argv[1]
        case "*.tar.gz"
            tar xzf $argv[1]
        case "*.bz2"
            bunzip2 $argv[1]
        case "*.rar"
            unrar x $argv[1]
        case "*.gz"
            gunzip $argv[1]
        case "*.tar"
            tar xf $argv[1]
        case "*.tbz2"
            tar xjf $argv[1]
        case "*.tgz"
            tar xzf $argv[1]
        case "*.zip"
            unzip $argv[1]
        case "*.Z"
            uncompress $argv[1]
        case "*.7z"
            7z x $argv[1]
        case '*'
            echo "'$argv[1]' cannot be extracted via extract()"
    end
end

function backup
    if test (count $argv) -eq 0
        echo "Usage: backup <file>"
        return 1
    end
    cp $argv[1] $argv[1].bak
    echo "Backup created: $argv[1].bak"
end

function weather
    if test (count $argv) -eq 0
        curl -s "wttr.in/?format=3"
    else
        curl -s "wttr.in/$argv[1]?format=3"
    end
end

# Dotfiles management
function dotfiles
    git --git-dir=$HOME/.dotfiles/.git --work-tree=$HOME $argv
end

# Quick navigation to common directories
function goto_config
    cd ~/.config
end

function goto_downloads
    cd ~/Downloads
end

function goto_documents
    cd ~/Documents
end

function goto_pictures
    cd ~/Pictures
end

# System information
function sysinfo
    echo "System Information:"
    echo "=================="
    if command -q fastfetch
        fastfetch
    else if command -q neofetch
        neofetch
    else
        echo "OS: "(uname -o)
        echo "Kernel: "(uname -r)
        echo "Architecture: "(uname -m)
        echo "Hostname: "(hostname)
        echo "Uptime: "(uptime -p)
    end
end

# Theme management
function apply_theme
    if test (count $argv) -eq 0
        echo "Usage: apply_theme <wallpaper_path>"
        return 1
    end
    
    if test -f $argv[1]
        matugen image $argv[1]
        hyprctl hyprpaper wallpaper ",$argv[1]"
        echo "Theme applied with wallpaper: $argv[1]"
    else
        echo "File not found: $argv[1]"
        return 1
    end
end

# Initialize zoxide if available
if command -q zoxide
    zoxide init fish | source
    alias cd='z'
end

# Initialize starship prompt if available
if command -q starship
    starship init fish | source
end

# Initialize fzf key bindings if available
if command -q fzf
    if test -f /usr/share/fzf/key-bindings.fish
        source /usr/share/fzf/key-bindings.fish
    end
    if test -f /usr/share/fzf/completion.fish
        source /usr/share/fzf/completion.fish
    end
end

# Fish syntax highlighting
set -g fish_color_normal cdd6f4
set -g fish_color_command 89b4fa
set -g fish_color_keyword f38ba8
set -g fish_color_quote a6e3a1
set -g fish_color_redirection f5c2e7
set -g fish_color_end fab387
set -g fish_color_error f38ba8
set -g fish_color_param f2cdcd
set -g fish_color_comment 6c7086
set -g fish_color_selection --background=313244
set -g fish_color_search_match --background=313244
set -g fish_color_operator f5c2e7
set -g fish_color_escape eba0ac
set -g fish_color_autosuggestion 6c7086

# Fish pager colors
set -g fish_pager_color_progress 6c7086
set -g fish_pager_color_prefix 89b4fa
set -g fish_pager_color_completion cdd6f4
set -g fish_pager_color_description 6c7086

# Load custom functions if they exist
if test -d ~/.config/fish/functions
    for file in ~/.config/fish/functions/*.fish
        source $file
    end
end

# Welcome message
if status is-interactive
    echo ""
    echo "Welcome to Fish Shell on Hyprland! 🐟"
    echo "Type 'sysinfo' for system information"
    echo "Type 'help' for Fish help"
    echo ""
end
