# Fish Shell Color Configuration - Generated by Matugen
# Source: {{image_path}}

# Set fish shell colors based on generated theme
set -U fish_color_normal {{colors.on_surface.default.hex_stripped}}
set -U fish_color_command {{colors.primary.default.hex_stripped}}
set -U fish_color_quote {{colors.secondary.default.hex_stripped}}
set -U fish_color_redirection {{colors.tertiary.default.hex_stripped}}
set -U fish_color_end {{colors.primary.default.hex_stripped}}
set -U fish_color_error {{colors.error.default.hex_stripped}}
set -U fish_color_param {{colors.on_surface.default.hex_stripped}}
set -U fish_color_comment {{colors.outline.default.hex_stripped}}
set -U fish_color_match --background={{colors.primary_container.default.hex_stripped}}
set -U fish_color_selection white --bold --background={{colors.primary.default.hex_stripped}}
set -U fish_color_search_match bryellow --background={{colors.secondary_container.default.hex_stripped}}
set -U fish_color_history_current --bold
set -U fish_color_operator {{colors.secondary.default.hex_stripped}}
set -U fish_color_escape {{colors.tertiary.default.hex_stripped}}
set -U fish_color_cwd {{colors.primary.default.hex_stripped}}
set -U fish_color_cwd_root {{colors.error.default.hex_stripped}}
set -U fish_color_valid_path --underline
set -U fish_color_autosuggestion {{colors.outline.default.hex_stripped}}
set -U fish_color_user {{colors.secondary.default.hex_stripped}}
set -U fish_color_host {{colors.primary.default.hex_stripped}}
set -U fish_color_cancel -r
set -U fish_pager_color_completion {{colors.on_surface.default.hex_stripped}}
set -U fish_pager_color_description {{colors.outline.default.hex_stripped}} yellow
set -U fish_pager_color_prefix white --bold --underline
set -U fish_pager_color_progress brwhite --background={{colors.primary.default.hex_stripped}}

# Set LS_COLORS for better file listing
set -x LS_COLORS "rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32"