# Fish Shell Dynamic Colors
# Auto-generated by Matugen

# Set fish colors based on Material You palette
set -g fish_color_normal {{colors.foreground.default.hex}}
set -g fish_color_command {{colors.primary.default.hex}}
set -g fish_color_keyword {{colors.error.default.hex}}
set -g fish_color_quote {{colors.tertiary.default.hex}}
set -g fish_color_redirection {{colors.secondary.default.hex}}
set -g fish_color_end {{colors.secondary_bright.default.hex}}
set -g fish_color_error {{colors.error.default.hex}}
set -g fish_color_param {{colors.on_surface.default.hex}}
set -g fish_color_comment {{colors.on_surface_variant.default.hex}}
set -g fish_color_selection --background={{colors.surface_bright.default.hex}}
set -g fish_color_search_match --background={{colors.surface_bright.default.hex}}
set -g fish_color_operator {{colors.secondary.default.hex}}
set -g fish_color_escape {{colors.tertiary_bright.default.hex}}
set -g fish_color_autosuggestion {{colors.on_surface_variant.default.hex}}
set -g fish_color_cancel {{colors.error.default.hex}}

# Pager colors
set -g fish_pager_color_progress {{colors.on_surface_variant.default.hex}}
set -g fish_pager_color_prefix {{colors.primary.default.hex}}
set -g fish_pager_color_completion {{colors.foreground.default.hex}}
set -g fish_pager_color_description {{colors.on_surface_variant.default.hex}}
set -g fish_pager_color_selected_background --background={{colors.surface_bright.default.hex}}
set -g fish_pager_color_selected_prefix {{colors.primary_bright.default.hex}}
set -g fish_pager_color_selected_completion {{colors.foreground.default.hex}}
set -g fish_pager_color_selected_description {{colors.on_surface.default.hex}}

# History search colors
set -g fish_color_history_current {{colors.primary.default.hex}}

# Match colors
set -g fish_color_match {{colors.tertiary.default.hex}}

# Valid path color
set -g fish_color_valid_path --underline

# Additional color customizations
set -g fish_color_cwd {{colors.primary.default.hex}}
set -g fish_color_cwd_root {{colors.error.default.hex}}
set -g fish_color_user {{colors.secondary.default.hex}}
set -g fish_color_host {{colors.tertiary.default.hex}}
set -g fish_color_host_remote {{colors.secondary_bright.default.hex}}
set -g fish_color_status {{colors.error.default.hex}}

# Apply prompt colors for starship if available
if command -q starship
    set -gx STARSHIP_CONFIG ~/.config/starship/starship.toml
end

# Export colors for other applications
set -gx LS_COLORS "di={{colors.primary.default.hex}}:fi={{colors.foreground.default.hex}}:ln={{colors.secondary.default.hex}}:pi={{colors.tertiary.default.hex}}:so={{colors.tertiary.default.hex}}:bd={{colors.secondary_bright.default.hex}}:cd={{colors.secondary_bright.default.hex}}:or={{colors.error.default.hex}}:mi={{colors.error.default.hex}}:ex={{colors.primary_bright.default.hex}}"

# Set environment variables for consistent theming
set -gx THEME_PRIMARY {{colors.primary.default.hex}}
set -gx THEME_SECONDARY {{colors.secondary.default.hex}}
set -gx THEME_TERTIARY {{colors.tertiary.default.hex}}
set -gx THEME_BACKGROUND {{colors.background.default.hex}}
set -gx THEME_FOREGROUND {{colors.foreground.default.hex}}
set -gx THEME_SURFACE {{colors.surface.default.hex}}
set -gx THEME_ERROR {{colors.error.default.hex}}

# Update terminal title with theme info
function fish_title
    set -l theme_indicator "🎨"
    if test (count $argv) -gt 0
        echo "$theme_indicator $argv[1]"
    else
        echo "$theme_indicator "(prompt_pwd)
    end
end
